// This is a program used to print undocumented constants

#include <Windows.h>
#include <iostream>

#define PRINT_VAL(val) std::cout << #val " :: " << val << ";" << std::endl

int main ()
{
	PRINT_VAL (LANG_SYSTEM_DEFAULT);
	PRINT_VAL (LANG_USER_DEFAULT);
	PRINT_VAL (LANG_NEUTRAL);
	PRINT_VAL (SUBLANG_NEUTRAL);
	PRINT_VAL (SUBLANG_DEFAULT);
	PRINT_VAL (SUBLANG_SYS_DEFAULT);
	PRINT_VAL (SUBLANG_CUSTOM_DEFAULT);
	PRINT_VAL (SUBLANG_CUSTOM_UNSPECIFIED);
	PRINT_VAL (SUBLANG_UI_CUSTOM_DEFAULT);
	PRINT_VAL (MEMORY_ALLOCATION_ALIGNMENT);
	PRINT_VAL (KF_ALTDOWN);
	PRINT_VAL (KF_DLGMODE);
	PRINT_VAL (KF_EXTENDED);
	PRINT_VAL (KF_MENUMODE);
	PRINT_VAL (KF_REPEAT);
	PRINT_VAL (KF_UP);
	PRINT_VAL (FOREGROUND_BLUE);
	PRINT_VAL (FOREGROUND_GREEN);
	PRINT_VAL (FOREGROUND_RED);
	PRINT_VAL (FOREGROUND_INTENSITY);
	PRINT_VAL (BACKGROUND_BLUE);
	PRINT_VAL (BACKGROUND_GREEN);
	PRINT_VAL (BACKGROUND_RED);
	PRINT_VAL (BACKGROUND_INTENSITY);
	PRINT_VAL (COMMON_LVB_LEADING_BYTE);
	PRINT_VAL (COMMON_LVB_TRAILING_BYTE);
	PRINT_VAL (COMMON_LVB_GRID_HORIZONTAL);
	PRINT_VAL (COMMON_LVB_GRID_LVERTICAL);
	PRINT_VAL (COMMON_LVB_GRID_RVERTICAL);
	PRINT_VAL (COMMON_LVB_REVERSE_VIDEO);
	PRINT_VAL (COMMON_LVB_UNDERSCORE);
	PRINT_VAL (INFINITE);
	PRINT_VAL (WAIT_OBJECT_0);
	PRINT_VAL (STATUS_WAIT_0);
	PRINT_VAL (WAIT_ABANDONED_0);
	PRINT_VAL (STATUS_ABANDONED_WAIT_0);
	PRINT_VAL (WAIT_TIMEOUT);
	PRINT_VAL (WAIT_FAILED);

	return 0;
}
